### ISSUE TITLE
Support for "Compound glyphs"

### ISSUE THREAD

**Issue by k-omura** [k-omura/truetype_Arduino#13]
Gradually support "Compound glyphs"
Initially planned without scaling support

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM01/Chap1.html#compound

**Comment by k-omura** [comment]
Supports the following flags in "Table 18: Component flags"
- ARG_1_AND_2_ARE_WORDS
- ARGS_ARE_XY_VALUES
- (ROUND_XY_TO_GRID)
- WE_HAVE_A_SCALE
- MORE_COMPONENTS
- USE_MY_METRICS

**Comment by Yardie-** [comment]
Thanks K I'll check it out
