### ISSUE TITLE
Request for complete example

### ISSUE THREAD

**Issue by savikko** [k-omura/truetype_Arduino#14]
First of all, thanks for creating this!

I am totally beginner within ESP32 development and currently have played with GxEPD library (using e-paper display).

I see you have demo on 2.9" waveshare display. Could you provide full example code to get a clue how that fully works?

My real question might be how to write framebuffer to display, but I am too shy to ask that :)

**Comment by k-omura** [comment]
Thank for your request.
I would like to help you display it on your e-paper.

I took a look at GxEPD.  Can it be used with GxEPD?  I understood that it was a request.  I saw GxEPD for the first time, so I will answer again after understanding a little^_^
https://github.com/ZinggJM/GxEPD

Try examples/truetypeToSerialTest if you like!
I think you'll get a better understanding of framebuffers!

Thank you.

**Comment by k-omura** [comment]
After some research, I found that GxEPD is an extension of Adafruit GFX. That is, the methods of the Adafruit GFX class are available.

Therefore, the solution will use drawBitmap() pasted at the bottom. Replace the FLASH_TO_SCREEN() of the sample code provided by truetype_Arduino (luckily, the sample code can be used as it is for other settings).

I'm not in a situation I can see this right away, but can I try it in @savikko 's environment?

Truetype_Arduino sample code:
https://github.com/k-omura/truetype_Arduino/blob/master/examples/truetypeToSerialTest/truetypeToSerialTest.ino

Bridge to Adafruit GFX:
http://adafruit.github.io/Adafruit-GFX-Library/html/class_adafruit___g_f_x.html#a805a15f1b3ea9eff5d1666b8e6db1c56

**Comment by savikko** [comment]
Oh well, I think I was temporarily blind as I did not notice those examples there.

This answers my questions, will try with drawBitmap.

Thank you.
