### ISSUE TITLE
The demo of this library used on the Lilygo EPD47

### ISSUE THREAD

**Issue by kunc0** [k-omura/truetype_Arduino#15]
Hello, I am very interested in your work, can you upload the DEMO of this library used on the Lilygo EPD47 (or other display devices )? 

Many thanks!

**Comment by k-omura** [comment]
thank you for having interest.  I will arrange and upload the sample for Lilygo EPD47.  I will contact you when it is up and close this issue.

**Comment by k-omura** [comment]
@KKCaren
I uploaded it here. Please check!
https://github.com/k-omura/truetype_Arduino/tree/master/examples/LirygoEPD47
