### ISSUE TITLE
2 SMALL BUGS

### ISSUE THREAD

**Issue by igrinon** [k-omura/truetype_Arduino#2]
Hello, I've found 2 small bugs:

At: readCoords
 else if (~glyph.points[i].flag & sameFlag) {
      int16_t off=getInt16t();      //FOR ESP32 SIGNED MUST BE USED
      value += off;

At: generateBitmap
  this->points = NULL;
  this->beginPoints = NULL;  //FOR ESP32 MUST BE ADDED
  this->endPoints = NULL;     //FOR ESP32 MUST BE ADDED

Thanks for this good code!!!!

**Comment by k-omura** [comment]
Thank you for pointing out the bug!
Is it okay to understand that it is a special correction part in the case of ESP32?
It will be corrected and reflected later.

Best regards.
