### ISSUE TITLE
Feature request SPIFFS

### ISSUE THREAD

**Issue by Yardie-** [k-omura/truetype_Arduino#3]
This is excellent I have been converting my ttfs to rle code to display from arduino nanos to many epaper displays (especially partial display units to allow changes is small areas of the screen). 
This has been limited to one font size.
Having moved to ESP32s now this is exactly what I was looking for.
As the ESP32s have so much SPIFFS space have you considered storing the ttf there.
I am new to the ESP chips and SPIFFS so it is not clear to me yet how to do this.
I have only just found your code and as such am not familiar with it. I will rectify this soon.
So feature request is simply 

Store and read ttf font/s in SPIFFS
Thanks heaps for your code. 
:) Greg

**Comment by k-omura** [comment]
thank you for the request!
I was late because I didn't notice your comment.

I think it's a good idea to read ttf from SPIFFS!
I'm currently working on another project, so I don't know if I can answer the request immediately, but I want to challenge!

Your experience is great so please support me!
Best regards (^^)v

**Comment by Yardie-** [comment]
I will do my best I love that his does not require all the overhead of the adafruit graphics library. Variable height TTF epaper very cool indeed.

**Comment by k-omura** [comment]
Added support for ESP32 SPIFFS.
Check out the sample code for ILI9341 (not for STM32).

In the past, SD was input to the library, but this time, by inputting with File, it was possible to support all input methods, not limited to SD and SPIFFS.

Thanks to your ideas, it's more versatile!
Let me know if you have any bugs or new ideas!

**Comment by Yardie-** [comment]
Cool Thanks heaps  I'll give it a go this week.
