### ISSUE TITLE
Ok What have I done wrong

### ISSUE THREAD

**Issue by Yardie-** [k-omura/truetype_Arduino#7]
I built a simple sketch to demonstrate the library
It compiles fine but then fails with
assertion "heap != NULL && "realloc() pointer is outside heap areas"
I have run the exception decoder but that doesn't point to which realloc is throwing the error.
I have attached my sketch file.
[test.ino.txt](https://github.com/k-omura/truetype_Arduino/files/6424534/test.ino.txt)

This is the bit where cpp eludes me.

**Comment by Yardie-** [comment]
Ok after a bit of fiddling and a few
```
 Serial.print("\nStart of\t");
 Serial.println(__FUNCTION__);
```
 I found the point where it dies
line 851 
`this->endPoints = (int *)realloc(this->endPoints, sizeof(int) * this->numEndPoints);
`
just before this 
```
 this->numEndPoints++; 
Serial.println(this->numEndPoints);  //at this point numEndPoints == 1

```
Also 
I replaced a few NULL with '\0' in the uint??_t assignments which is effectively the same thing AFAIK
That stopped the following  warnings but not the error.

```
In file included from /tmp/arduino_build_27813/sketch/truetype_Arduino.cpp:8:0:
/tmp/arduino_build_27813/sketch/truetype_Arduino.h:182:29: warning: converting to non-pointer type 'uint32_t {aka unsigned int}' from NULL [-Wconversion-null]
     uint32_t hmtxTablePos = NULL;
                             ^
/tmp/arduino_build_27813/sketch/truetype_Arduino.h:190:29: warning: converting to non-pointer type 'uint32_t {aka unsigned int}' from NULL [-Wconversion-null]
     uint32_t kernTablePos = NULL;
                             ^
In file included from /home/g/code/Arduino/ESP32/TTF/test/test.ino:3:0:
/tmp/arduino_build_27813/sketch/truetype_Arduino.h:182:29: warning: converting to non-pointer type 'uint32_t {aka unsigned int}' from NULL [-Wconversion-null]
     uint32_t hmtxTablePos = NULL;
                             ^
/tmp/arduino_build_27813/sketch/truetype_Arduino.h:190:29: warning: converting to non-pointer type 'uint32_t {aka unsigned int}' from NULL [-Wconversion-null]
     uint32_t kernTablePos = NULL;
                             ^
/tmp/arduino_build_27813/sketch/truetype_Arduino.cpp: In member function 'void truetypeClass::string(uint16_t, uint16_t, const wchar_t*)':
/tmp/arduino_build_27813/sketch/truetype_Arduino.cpp:734:24: warning: converting to non-pointer type 'uint16_t {aka short unsigned int}' from NULL [-Wconversion-null]
   uint16_t prev_code = NULL;
                        ^
/tmp/arduino_build_27813/sketch/truetype_Arduino.cpp:739:17: warning: converting to non-pointer type 'uint16_t {aka short unsigned int}' from NULL [-Wconversion-null]
       prev_code = NULL;
                 ^
/tmp/arduino_build_27813/sketch/truetype_Arduino.cpp:750:21: warning: NULL used in arithmetic [-Wpointer-arith]
     if(prev_code != NULL && this->kerningOn){
```

**Comment by k-omura** [comment]
Thank you for checking out!
I am also investigating here.
One thing I found is the code below that is currently defined in setup ().
```
// TrueType class declaration
truetypeClass truetype = truetypeClass ();
```
When I tried to get it out of setup (), the error disappeared.
code [here](https://github.com/k-omura/truetype_Arduino/blob/master/examples/truetypeToSerialTest/truetypeToSerialTest.ino) 
It seems that it was a scope problem, but I haven't found out where the problem was.
On the other hand, in actual use, I think that truetypeClass is not set to the scope used only in setup () (used in loop () etc.).

I felt that it was a good example code to put out fonts on the serial, so I will set it to the library's example 👍

**Comment by Yardie-** [comment]
Lots of libraries are setup in the global scope. 
Not great but pretty normal.
Ok I'll just use it in the global scope for now. 
Well done and thanks for working so hard on this.
I'll try to help where I can.
I hacked out that serial version when I was trying to debug my own code. I thought it might be useful to stop the why can' I see it when the problem has nothing to do with the framebuffer at all.
Obviously I forgot add the call to it in the code but that was a pretty clear mistake.
